### ISSUE TITLE
Renaming of a module

### ISSUE THREAD

**Issue by developers-desk** [Shreyas3108/house-price-prediction#3]
In the model `from sklearn.cross_validation import train_test_split` should be `from sklearn.model_selection import train_test_split` as the module name is changed if we don't do that it will through an error.

Hope this will help others.
Cheers.

**Comment by Shreyas3108** [comment]
Sure , Will update the code and close the issue. Thanks for contributing.

**Comment by Shreyas3108** [comment]
Hi @sonichandni , 

Changed to model_selection. Thank you keeping the repo alive.

**Comment by Bacancy-Chandni** [comment]
Your welcome :+1:

**Comment by developers-desk** [comment]
You're welcome 👍🏻
